### Crear un nuevo usuario
POST http://localhost:5000/api/usuarios/registrar
Content-Type: application/json

{
  "nombre": "Usuario2",
  "email": "usuario2@prueba.com",
  "password": "Usuario123"
}
### Iniciar sesión
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "salas",
  "password": "Usuario123"
}

### Crear un nuevo gasto
POST http://localhost:5000/api/gastos/nuevoGasto
Content-Type: application/json

{
  "fecha": "2024-07-01",
  "concepto": "Comida",
  "monto": 50,
  "usuarioId": "68bb90c3527e1975f559154b"
}
### Obtener gastos del mes actual para un usuario
GET http://localhost:5000/api/gastos/68bf799928ea61737b894518
Accept: application/json

### Eliminar un gasto
DELETE http://localhost:5000/api/gastos/eliminar
Content-Type: application/json

{
  "usuarioId": "68bf799928ea61737b894518",
  "gastoId": "68bf96c16b6f835db322734a"
}
####eventos
### crear evento
POST http://localhost:5000/api/eventos/nuevoEvento
Content-Type: application/json

{
  "fecha":"2025-09-15",
  "incluirReciboEnVenta":false ,
  "contarReciboComoPago":false ,
  "pagoRecibo": 0,
  "pagoQR": 2000 ,
  "pagoBaucher": 2000 ,
  "pagoEfectivo":2000 ,
  "montoSistema": 6000,
  "propina": 200 ,
  "gananciaPorcentaje": 300 ,
  "gananciaGeneral": 300 ,
  "usuario":"68bf799928ea61737b894518"
}
### traer datos del mes actual
GET http://localhost:5000/api/eventos/68bf799928ea61737b894518
Accept: application/json

### Obtener eventos de un mes seleccionado para un usuario
GET http://localhost:5000/api/eventos/mes/68bf799928ea61737b894518/09
Accept: application/json

